/**
 * Fetches the official Mailchimp Marketing API OpenAPI spec and generates
 * src/api-catalog.ts with a typed array of all endpoints.
 *
 * Run: npm run generate-catalog
 */

import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const SPEC_URL =
  "https://raw.githubusercontent.com/mailchimp/mailchimp-client-lib-codegen/main/spec/marketing.json";

interface OpenAPISpec {
  paths: Record<
    string,
    Record<
      string,
      {
        summary?: string;
        tags?: string[];
        parameters?: Array<{
          name: string;
          in: string;
          required?: boolean;
        }>;
        requestBody?: unknown;
      }
    >
  >;
}

interface CatalogEntry {
  method: string;
  path: string;
  summary: string;
  tag: string;
  pathParams: string[];
  queryParams: string[];
  hasBody: boolean;
}

const TAG_DESCRIPTIONS: Record<string, string> = {
  accountExport: "Export account data",
  accountExports: "List account exports",
  activityFeed: "Activity feed events",
  authorizedApps: "OAuth authorized applications",
  automations: "Marketing automation workflows and triggered emails",
  batchWebhooks: "Batch webhook configurations",
  batches: "Batch operations for bulk API calls",
  campaignFolders: "Organize campaigns into folders",
  campaigns: "Email campaigns — create, schedule, send, content, feedback",
  connectedSites: "Connected e-commerce sites",
  conversations: "Conversation tracking and messages",
  customerJourneys: "Customer journey automations",
  ecommerce: "E-commerce stores, products, orders, carts, customers",
  facebookAds: "Facebook ad campaigns",
  fileManager: "File and image uploads",
  landingPages: "Landing page management",
  lists: "Audiences — members, segments, merge fields, tags, webhooks, signups",
  ping: "API health check",
  reporting: "Advanced reporting and analytics",
  reports: "Campaign performance reports — opens, clicks, bounces",
  root: "API root and account info",
  searchCampaigns: "Search campaigns by query",
  searchMembers: "Search audience members by query",
  surveyQuestions: "Survey question management",
  surveyResponses: "Survey response data",
  surveys: "Survey management",
  templateFolders: "Organize templates into folders",
  templates: "Email templates — create, update, manage",
  verifiedDomains: "Domain verification for sending",
};

async function main() {
  console.log("Fetching Mailchimp Marketing API spec...");
  const resp = await fetch(SPEC_URL);
  if (!resp.ok) {
    throw new Error(`Failed to fetch spec: ${resp.status} ${resp.statusText}`);
  }

  const spec: OpenAPISpec = await resp.json();
  const catalog: CatalogEntry[] = [];
  const tags = new Set<string>();

  for (const [path, methods] of Object.entries(spec.paths)) {
    // Collect path-level parameters
    const pathLevelParams = (methods as Record<string, unknown>).parameters as
      | Array<{ name: string; in: string }>
      | undefined;

    for (const [method, operation] of Object.entries(methods)) {
      if (method === "parameters" || method === "x-]") continue;
      if (typeof operation !== "object" || !operation) continue;
      if (!("summary" in operation)) continue;

      const op = operation as {
        summary?: string;
        tags?: string[];
        parameters?: Array<{ name: string; in: string; required?: boolean }>;
        requestBody?: unknown;
      };

      const tag = op.tags?.[0] ?? "other";
      tags.add(tag);

      // Merge path-level and operation-level parameters
      const allParams = [...(pathLevelParams ?? []), ...(op.parameters ?? [])];

      const pathParams = allParams
        .filter((p) => p.in === "path")
        .map((p) => p.name);

      const queryParams = allParams
        .filter((p) => p.in === "query")
        .map((p) => p.name);

      const hasBody = !!op.requestBody;

      catalog.push({
        method: method.toUpperCase(),
        path,
        summary: op.summary ?? "",
        tag,
        pathParams,
        queryParams,
        hasBody,
      });
    }
  }

  // Sort by tag, then path, then method
  catalog.sort((a, b) => {
    if (a.tag !== b.tag) return a.tag.localeCompare(b.tag);
    if (a.path !== b.path) return a.path.localeCompare(b.path);
    return a.method.localeCompare(b.method);
  });

  const sortedTags = [...tags].sort();

  // Generate TypeScript file
  const output = `// Auto-generated by scripts/generate-catalog.ts — do not edit manually
// Source: ${SPEC_URL}
// Generated: ${new Date().toISOString()}

import type { CatalogEntry } from "./types.js";

export const API_CATALOG: CatalogEntry[] = ${JSON.stringify(catalog, null, 2)} as const;

export const ALL_TAGS: string[] = ${JSON.stringify(sortedTags)};

export const TAG_DESCRIPTIONS: Record<string, string> = ${JSON.stringify(TAG_DESCRIPTIONS, null, 2)};
`;

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(__dirname, "../src/api-catalog.ts");
  writeFileSync(outPath, output, "utf-8");

  console.log(`Generated ${outPath}`);
  console.log(`  ${catalog.length} endpoints across ${sortedTags.length} tags`);
  console.log(`  Tags: ${sortedTags.join(", ")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
