// Auto-generated by scripts/generate-catalog.ts — do not edit manually
// Source: https://raw.githubusercontent.com/mailchimp/mailchimp-client-lib-codegen/main/spec/marketing.json
// Generated: 2026-03-10T17:33:57.023Z

import type { CatalogEntry } from "./types.js";

export const API_CATALOG: CatalogEntry[] = [
  {
    "method": "GET",
    "path": "/account-exports/{export_id}",
    "summary": "Get account export info",
    "tag": "accountExport",
    "pathParams": [
      "export_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/account-exports",
    "summary": "List account exports",
    "tag": "accountExports",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/account-exports",
    "summary": "Add export",
    "tag": "accountExports",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/activity-feed/chimp-chatter",
    "summary": "Get latest chimp chatter",
    "tag": "activityFeed",
    "pathParams": [],
    "queryParams": [
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/audiences/{audience_id}/contacts",
    "summary": "Get Contacts",
    "tag": "audiences",
    "pathParams": [
      "audience_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "cursor",
      "created_before",
      "created_since",
      "updated_before",
      "updated_since",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/audiences/{audience_id}/contacts",
    "summary": "Add Contact",
    "tag": "audiences",
    "pathParams": [
      "audience_id"
    ],
    "queryParams": [
      "merge_field_validation_mode",
      "data_mode"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/audiences/{audience_id}/contacts/{contact_id}",
    "summary": "Get Contact",
    "tag": "audiences",
    "pathParams": [
      "audience_id",
      "contact_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/audiences/{audience_id}/contacts/{contact_id}",
    "summary": "Update Contact",
    "tag": "audiences",
    "pathParams": [
      "audience_id",
      "contact_id"
    ],
    "queryParams": [
      "merge_field_validation_mode",
      "data_mode"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/authorized-apps",
    "summary": "List authorized apps",
    "tag": "authorizedApps",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/authorized-apps/{app_id}",
    "summary": "Get authorized app info",
    "tag": "authorizedApps",
    "pathParams": [
      "app_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations",
    "summary": "List automations",
    "tag": "automations",
    "pathParams": [],
    "queryParams": [
      "count",
      "offset",
      "fields",
      "exclude_fields",
      "before_create_time",
      "since_create_time",
      "before_start_time",
      "since_start_time",
      "status"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations",
    "summary": "Add automation",
    "tag": "automations",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations/{workflow_id}",
    "summary": "Get automation info",
    "tag": "automations",
    "pathParams": [
      "workflow_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations/{workflow_id}/actions/archive",
    "summary": "Archive automation",
    "tag": "automations",
    "pathParams": [
      "workflow_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations/{workflow_id}/actions/pause-all-emails",
    "summary": "Pause automation emails",
    "tag": "automations",
    "pathParams": [
      "workflow_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations/{workflow_id}/actions/start-all-emails",
    "summary": "Start automation emails",
    "tag": "automations",
    "pathParams": [
      "workflow_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations/{workflow_id}/emails",
    "summary": "List automated emails",
    "tag": "automations",
    "pathParams": [
      "workflow_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}",
    "summary": "Delete workflow email",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}",
    "summary": "Get workflow email info",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}",
    "summary": "Update workflow email",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}/actions/pause",
    "summary": "Pause automated email",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}/actions/start",
    "summary": "Start automated email",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}/queue",
    "summary": "List automated email subscribers",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}/queue",
    "summary": "Add subscriber to workflow email",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations/{workflow_id}/emails/{workflow_email_id}/queue/{subscriber_hash}",
    "summary": "Get automated email subscriber",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "workflow_email_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations/{workflow_id}/removed-subscribers",
    "summary": "List subscribers removed from workflow",
    "tag": "automations",
    "pathParams": [
      "workflow_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/automations/{workflow_id}/removed-subscribers",
    "summary": "Remove subscriber from workflow",
    "tag": "automations",
    "pathParams": [
      "workflow_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/automations/{workflow_id}/removed-subscribers/{subscriber_hash}",
    "summary": "Get subscriber removed from workflow",
    "tag": "automations",
    "pathParams": [
      "workflow_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/batches",
    "summary": "List batch requests",
    "tag": "batches",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/batches",
    "summary": "Start batch operation",
    "tag": "batches",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/batches/{batch_id}",
    "summary": "Delete batch request",
    "tag": "batches",
    "pathParams": [
      "batch_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/batches/{batch_id}",
    "summary": "Get batch operation status",
    "tag": "batches",
    "pathParams": [
      "batch_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/batch-webhooks",
    "summary": "List batch webhooks",
    "tag": "batchWebhooks",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/batch-webhooks",
    "summary": "Add batch webhook",
    "tag": "batchWebhooks",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/batch-webhooks/{batch_webhook_id}",
    "summary": "Delete batch webhook",
    "tag": "batchWebhooks",
    "pathParams": [
      "batch_webhook_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/batch-webhooks/{batch_webhook_id}",
    "summary": "Get batch webhook info",
    "tag": "batchWebhooks",
    "pathParams": [
      "batch_webhook_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/batch-webhooks/{batch_webhook_id}",
    "summary": "Update batch webhook",
    "tag": "batchWebhooks",
    "pathParams": [
      "batch_webhook_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaign-folders",
    "summary": "List campaign folders",
    "tag": "campaignFolders",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaign-folders",
    "summary": "Add campaign folder",
    "tag": "campaignFolders",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/campaign-folders/{folder_id}",
    "summary": "Delete campaign folder",
    "tag": "campaignFolders",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaign-folders/{folder_id}",
    "summary": "Get campaign folder",
    "tag": "campaignFolders",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/campaign-folders/{folder_id}",
    "summary": "Update campaign folder",
    "tag": "campaignFolders",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaigns",
    "summary": "List campaigns",
    "tag": "campaigns",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "type",
      "status",
      "before_send_time",
      "since_send_time",
      "before_create_time",
      "since_create_time",
      "list_id",
      "folder_id",
      "member_id",
      "sort_field",
      "sort_dir",
      "include_resend_shortcut_eligibility"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns",
    "summary": "Add campaign",
    "tag": "campaigns",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/campaigns/{campaign_id}",
    "summary": "Delete campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaigns/{campaign_id}",
    "summary": "Get campaign info",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "include_resend_shortcut_eligibility",
      "include_resend_shortcut_usage"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/campaigns/{campaign_id}",
    "summary": "Update campaign settings",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/cancel-send",
    "summary": "Cancel campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/create-resend",
    "summary": "Resend campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/pause",
    "summary": "Pause rss campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/replicate",
    "summary": "Replicate campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/resume",
    "summary": "Resume rss campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/schedule",
    "summary": "Schedule campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/send",
    "summary": "Send campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/test",
    "summary": "Send test email",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/actions/unschedule",
    "summary": "Unschedule campaign",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaigns/{campaign_id}/content",
    "summary": "Get campaign content",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PUT",
    "path": "/campaigns/{campaign_id}/content",
    "summary": "Set campaign content",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaigns/{campaign_id}/feedback",
    "summary": "List campaign feedback",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/campaigns/{campaign_id}/feedback",
    "summary": "Add campaign feedback",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/campaigns/{campaign_id}/feedback/{feedback_id}",
    "summary": "Delete campaign feedback message",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id",
      "feedback_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaigns/{campaign_id}/feedback/{feedback_id}",
    "summary": "Get campaign feedback message",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id",
      "feedback_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/campaigns/{campaign_id}/feedback/{feedback_id}",
    "summary": "Update campaign feedback message",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id",
      "feedback_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/campaigns/{campaign_id}/send-checklist",
    "summary": "Get campaign send checklist",
    "tag": "campaigns",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/connected-sites",
    "summary": "List connected sites",
    "tag": "connectedSites",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/connected-sites",
    "summary": "Add connected site",
    "tag": "connectedSites",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/connected-sites/{connected_site_id}",
    "summary": "Delete connected site",
    "tag": "connectedSites",
    "pathParams": [
      "connected_site_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/connected-sites/{connected_site_id}",
    "summary": "Get connected site",
    "tag": "connectedSites",
    "pathParams": [
      "connected_site_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/connected-sites/{connected_site_id}/actions/verify-script-installation",
    "summary": "Verify connected site script",
    "tag": "connectedSites",
    "pathParams": [
      "connected_site_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/audiences",
    "summary": "Get a list of audiences",
    "tag": "contacts",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/audiences/{audience_id}",
    "summary": "Get audience info",
    "tag": "contacts",
    "pathParams": [
      "audience_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/audiences/{audience_id}/contacts/{contact_id}/actions/archive",
    "summary": "Archive Contact",
    "tag": "contacts",
    "pathParams": [
      "audience_id",
      "contact_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/audiences/{audience_id}/contacts/{contact_id}/actions/forget",
    "summary": "Forget Contact",
    "tag": "contacts",
    "pathParams": [
      "audience_id",
      "contact_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/conversations",
    "summary": "List conversations",
    "tag": "conversations",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "has_unread_messages",
      "list_id",
      "campaign_id"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/conversations/{conversation_id}",
    "summary": "Get conversation",
    "tag": "conversations",
    "pathParams": [
      "conversation_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/conversations/{conversation_id}/messages",
    "summary": "List messages",
    "tag": "conversations",
    "pathParams": [
      "conversation_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "is_read",
      "before_timestamp",
      "since_timestamp"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/conversations/{conversation_id}/messages/{message_id}",
    "summary": "Get message",
    "tag": "conversations",
    "pathParams": [
      "conversation_id",
      "message_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/customer-journeys/journeys/{journey_id}/steps/{step_id}/actions/trigger",
    "summary": "Customer Journeys API trigger for a contact",
    "tag": "customerJourneys",
    "pathParams": [
      "journey_id",
      "step_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/orders",
    "summary": "List account orders",
    "tag": "ecommerce",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "campaign_id",
      "outreach_id",
      "customer_id",
      "has_outreach"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores",
    "summary": "List stores",
    "tag": "ecommerce",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores",
    "summary": "Add store",
    "tag": "ecommerce",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}",
    "summary": "Delete store",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}",
    "summary": "Get store info",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}",
    "summary": "Update store",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/carts",
    "summary": "List carts",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/carts",
    "summary": "Add cart",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}",
    "summary": "Delete cart",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}",
    "summary": "Get cart info",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}",
    "summary": "Update cart",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}/lines",
    "summary": "List cart line items",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}/lines",
    "summary": "Add cart line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}/lines/{line_id}",
    "summary": "Delete cart line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id",
      "line_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}/lines/{line_id}",
    "summary": "Get cart line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id",
      "line_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/carts/{cart_id}/lines/{line_id}",
    "summary": "Update cart line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "cart_id",
      "line_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/customers",
    "summary": "List customers",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "email_address"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/customers",
    "summary": "Add customer",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/customers/{customer_id}",
    "summary": "Delete customer",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "customer_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/customers/{customer_id}",
    "summary": "Get customer info",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "customer_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/customers/{customer_id}",
    "summary": "Update customer",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "customer_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PUT",
    "path": "/ecommerce/stores/{store_id}/customers/{customer_id}",
    "summary": "Add or update customer",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "customer_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/orders",
    "summary": "List orders",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "customer_id",
      "has_outreach",
      "campaign_id",
      "outreach_id"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/orders",
    "summary": "Add order",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}",
    "summary": "Delete order",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}",
    "summary": "Get order info",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}",
    "summary": "Update order",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PUT",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}",
    "summary": "Add or update order",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}/lines",
    "summary": "List order line items",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}/lines",
    "summary": "Add order line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}/lines/{line_id}",
    "summary": "Delete order line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id",
      "line_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}/lines/{line_id}",
    "summary": "Get order line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id",
      "line_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/orders/{order_id}/lines/{line_id}",
    "summary": "Update order line item",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "order_id",
      "line_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/products",
    "summary": "List product",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/products",
    "summary": "Add product",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}",
    "summary": "Delete product",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}",
    "summary": "Get product info",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}",
    "summary": "Update product",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PUT",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}",
    "summary": "Create or update product",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/images",
    "summary": "List product images",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/images",
    "summary": "Add product image",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/images/{image_id}",
    "summary": "Delete product image",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id",
      "image_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/images/{image_id}",
    "summary": "Get product image info",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id",
      "image_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/images/{image_id}",
    "summary": "Update product image",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id",
      "image_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/variants",
    "summary": "List product variants",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/variants",
    "summary": "Add product variant",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}",
    "summary": "Delete product variant",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id",
      "variant_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}",
    "summary": "Get product variant info",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id",
      "variant_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}",
    "summary": "Update product variant",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id",
      "variant_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PUT",
    "path": "/ecommerce/stores/{store_id}/products/{product_id}/variants/{variant_id}",
    "summary": "Add or update product variant",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "product_id",
      "variant_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/promo-rules",
    "summary": "List promo rules",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/promo-rules",
    "summary": "Add promo rule",
    "tag": "ecommerce",
    "pathParams": [
      "store_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}",
    "summary": "Delete promo rule",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "promo_rule_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}",
    "summary": "Get promo rule",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "promo_rule_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}",
    "summary": "Update promo rule",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "promo_rule_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes",
    "summary": "List promo codes",
    "tag": "ecommerce",
    "pathParams": [
      "promo_rule_id",
      "store_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes",
    "summary": "Add promo code",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "promo_rule_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes/{promo_code_id}",
    "summary": "Delete promo code",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "promo_rule_id",
      "promo_code_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes/{promo_code_id}",
    "summary": "Get promo code",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "promo_rule_id",
      "promo_code_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/ecommerce/stores/{store_id}/promo-rules/{promo_rule_id}/promo-codes/{promo_code_id}",
    "summary": "Update promo code",
    "tag": "ecommerce",
    "pathParams": [
      "store_id",
      "promo_rule_id",
      "promo_code_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/facebook-ads",
    "summary": "List facebook ads",
    "tag": "facebookAds",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/facebook-ads/{outreach_id}",
    "summary": "Get facebook ad info",
    "tag": "facebookAds",
    "pathParams": [
      "outreach_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/file-manager/files",
    "summary": "List stored files",
    "tag": "fileManager",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "type",
      "created_by",
      "before_created_at",
      "since_created_at",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/file-manager/files",
    "summary": "Add file",
    "tag": "fileManager",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/file-manager/files/{file_id}",
    "summary": "Delete file",
    "tag": "fileManager",
    "pathParams": [
      "file_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/file-manager/files/{file_id}",
    "summary": "Get file",
    "tag": "fileManager",
    "pathParams": [
      "file_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/file-manager/files/{file_id}",
    "summary": "Update file",
    "tag": "fileManager",
    "pathParams": [
      "file_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/file-manager/folders",
    "summary": "List folders",
    "tag": "fileManager",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "created_by",
      "before_created_at",
      "since_created_at"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/file-manager/folders",
    "summary": "Add folder",
    "tag": "fileManager",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/file-manager/folders/{folder_id}",
    "summary": "Delete folder",
    "tag": "fileManager",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/file-manager/folders/{folder_id}",
    "summary": "Get folder",
    "tag": "fileManager",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/file-manager/folders/{folder_id}",
    "summary": "Update folder",
    "tag": "fileManager",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/file-manager/folders/{folder_id}/files",
    "summary": "List stored files",
    "tag": "fileManager",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "type",
      "created_by",
      "before_created_at",
      "since_created_at",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/landing-pages",
    "summary": "List landing pages",
    "tag": "landingPages",
    "pathParams": [],
    "queryParams": [
      "sort_dir",
      "sort_field",
      "fields",
      "exclude_fields",
      "count"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/landing-pages",
    "summary": "Add landing page",
    "tag": "landingPages",
    "pathParams": [],
    "queryParams": [
      "use_default_list"
    ],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/landing-pages/{page_id}",
    "summary": "Delete landing page",
    "tag": "landingPages",
    "pathParams": [
      "page_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/landing-pages/{page_id}",
    "summary": "Get landing page info",
    "tag": "landingPages",
    "pathParams": [
      "page_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/landing-pages/{page_id}",
    "summary": "Update landing page",
    "tag": "landingPages",
    "pathParams": [
      "page_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/landing-pages/{page_id}/actions/publish",
    "summary": "Publish landing page",
    "tag": "landingPages",
    "pathParams": [
      "page_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/landing-pages/{page_id}/actions/unpublish",
    "summary": "Unpublish landing page",
    "tag": "landingPages",
    "pathParams": [
      "page_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/landing-pages/{page_id}/content",
    "summary": "Get landing page content",
    "tag": "landingPages",
    "pathParams": [
      "page_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists",
    "summary": "Get lists info",
    "tag": "lists",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "before_date_created",
      "since_date_created",
      "before_campaign_last_sent",
      "since_campaign_last_sent",
      "email",
      "sort_field",
      "sort_dir",
      "has_ecommerce_store",
      "include_total_contacts"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists",
    "summary": "Add list",
    "tag": "lists",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}",
    "summary": "Delete list",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}",
    "summary": "Get list info",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "include_total_contacts"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}",
    "summary": "Update lists",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}",
    "summary": "Batch subscribe or unsubscribe",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "skip_merge_validation",
      "skip_duplicate_check"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/abuse-reports",
    "summary": "List abuse reports",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/abuse-reports/{report_id}",
    "summary": "Get abuse report",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "report_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/activity",
    "summary": "List recent activity",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "count",
      "offset",
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/clients",
    "summary": "List top email clients",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/growth-history",
    "summary": "List growth history data",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/growth-history/{month}",
    "summary": "Get growth history by month",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "month"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/interest-categories",
    "summary": "List interest categories",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "type"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/interest-categories",
    "summary": "Add interest category",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}",
    "summary": "Delete interest category",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}",
    "summary": "Get interest category info",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}",
    "summary": "Update interest category",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}/interests",
    "summary": "List interests in category",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}/interests",
    "summary": "Add interest in category",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}/interests/{interest_id}",
    "summary": "Delete interest in category",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id",
      "interest_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}/interests/{interest_id}",
    "summary": "Get interest in category",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id",
      "interest_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}/interest-categories/{interest_category_id}/interests/{interest_id}",
    "summary": "Update interest in category",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "interest_category_id",
      "interest_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/locations",
    "summary": "List locations",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members",
    "summary": "List members info",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "email_type",
      "status",
      "since_timestamp_opt",
      "before_timestamp_opt",
      "since_last_changed",
      "before_last_changed",
      "unique_email_id",
      "vip_only",
      "interest_category_id",
      "interest_ids",
      "interest_match",
      "sort_field",
      "sort_dir",
      "since_last_campaign",
      "unsubscribed_since"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/members",
    "summary": "Add member to list",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "skip_merge_validation"
    ],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/members/{subscriber_hash}",
    "summary": "Archive list member",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}",
    "summary": "Get member info",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}/members/{subscriber_hash}",
    "summary": "Update list member",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "skip_merge_validation"
    ],
    "hasBody": false
  },
  {
    "method": "PUT",
    "path": "/lists/{list_id}/members/{subscriber_hash}",
    "summary": "Add or update list member",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "skip_merge_validation"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/members/{subscriber_hash}/actions/delete-permanent",
    "summary": "Delete list member",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}/activity",
    "summary": "View recent activity 50",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "action"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}/activity-feed",
    "summary": "View recent activity",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "activity_filters"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}/events",
    "summary": "List member events",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "count",
      "offset",
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/members/{subscriber_hash}/events",
    "summary": "Add event",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}/goals",
    "summary": "List member goal events",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}/notes",
    "summary": "List recent member notes",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "sort_field",
      "sort_dir",
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/members/{subscriber_hash}/notes",
    "summary": "Add member note",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/members/{subscriber_hash}/notes/{note_id}",
    "summary": "Delete note",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash",
      "note_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}/notes/{note_id}",
    "summary": "Get member note",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash",
      "note_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}/members/{subscriber_hash}/notes/{note_id}",
    "summary": "Update note",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash",
      "note_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/members/{subscriber_hash}/tags",
    "summary": "List member tags",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/members/{subscriber_hash}/tags",
    "summary": "Add or remove member tags",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/merge-fields",
    "summary": "List merge fields",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "type",
      "required"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/merge-fields",
    "summary": "Add merge field",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/merge-fields/{merge_id}",
    "summary": "Delete merge field",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "merge_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/merge-fields/{merge_id}",
    "summary": "Get merge field",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "merge_id"
    ],
    "queryParams": [
      "exclude_fields",
      "fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}/merge-fields/{merge_id}",
    "summary": "Update merge field",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "merge_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/segments",
    "summary": "List segments",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "type",
      "since_created_at",
      "before_created_at",
      "include_cleaned",
      "include_transactional",
      "include_unsubscribed",
      "since_updated_at",
      "before_updated_at"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/segments",
    "summary": "Add segment",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/segments/{segment_id}",
    "summary": "Delete segment",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "segment_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/segments/{segment_id}",
    "summary": "Get segment info",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "segment_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "include_cleaned",
      "include_transactional",
      "include_unsubscribed"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}/segments/{segment_id}",
    "summary": "Update segment",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "segment_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/segments/{segment_id}",
    "summary": "Batch add or remove members",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "segment_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/segments/{segment_id}/members",
    "summary": "List members in segment",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "segment_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "include_cleaned",
      "include_transactional",
      "include_unsubscribed"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/segments/{segment_id}/members",
    "summary": "Add member to segment",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "segment_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/segments/{segment_id}/members/{subscriber_hash}",
    "summary": "Remove list member from segment",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "segment_id",
      "subscriber_hash"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/signup-forms",
    "summary": "List signup forms",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/signup-forms",
    "summary": "Customize signup form",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/surveys",
    "summary": "Get information about all surveys for a list",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/surveys/{survey_id}",
    "summary": "Get survey",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "survey_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/tag-search",
    "summary": "Search for tags on a list by name.",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [
      "name"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/webhooks",
    "summary": "List webhooks",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/webhooks",
    "summary": "Add webhook",
    "tag": "lists",
    "pathParams": [
      "list_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/lists/{list_id}/webhooks/{webhook_id}",
    "summary": "Delete webhook",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "webhook_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/lists/{list_id}/webhooks/{webhook_id}",
    "summary": "Get webhook info",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "webhook_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/lists/{list_id}/webhooks/{webhook_id}",
    "summary": "Update webhook",
    "tag": "lists",
    "pathParams": [
      "list_id",
      "webhook_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/ping",
    "summary": "Ping",
    "tag": "ping",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/facebook-ads",
    "summary": "List facebook ads reports",
    "tag": "reporting",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/facebook-ads/{outreach_id}",
    "summary": "Get facebook ad report",
    "tag": "reporting",
    "pathParams": [
      "outreach_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/facebook-ads/{outreach_id}/ecommerce-product-activity",
    "summary": "List facebook ecommerce report",
    "tag": "reporting",
    "pathParams": [
      "outreach_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "sort_field"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/landing-pages",
    "summary": "List landing pages reports",
    "tag": "reporting",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/landing-pages/{outreach_id}",
    "summary": "Get landing page report",
    "tag": "reporting",
    "pathParams": [
      "outreach_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/surveys",
    "summary": "List survey reports",
    "tag": "reporting",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/surveys/{survey_id}",
    "summary": "Get survey report",
    "tag": "reporting",
    "pathParams": [
      "survey_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/surveys/{survey_id}/questions",
    "summary": "List survey question reports",
    "tag": "reporting",
    "pathParams": [
      "survey_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/surveys/{survey_id}/questions/{question_id}",
    "summary": "Get survey question report",
    "tag": "reporting",
    "pathParams": [
      "survey_id",
      "question_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/surveys/{survey_id}/questions/{question_id}/answers",
    "summary": "List answers for question",
    "tag": "reporting",
    "pathParams": [
      "survey_id",
      "question_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "respondent_familiarity_is"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/surveys/{survey_id}/responses",
    "summary": "List survey responses",
    "tag": "reporting",
    "pathParams": [
      "survey_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "answered_question",
      "chose_answer",
      "respondent_familiarity_is"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reporting/surveys/{survey_id}/responses/{response_id}",
    "summary": "Get survey response",
    "tag": "reporting",
    "pathParams": [
      "survey_id",
      "response_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports",
    "summary": "List campaign reports",
    "tag": "reports",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "type",
      "before_send_time",
      "since_send_time"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}",
    "summary": "Get campaign report",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/abuse-reports",
    "summary": "List abuse reports",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/abuse-reports/{report_id}",
    "summary": "Get abuse report",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "report_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/advice",
    "summary": "List campaign feedback",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/click-details",
    "summary": "List campaign details",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/click-details/{link_id}",
    "summary": "Get campaign link details",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "link_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/click-details/{link_id}/members",
    "summary": "List clicked link subscribers",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "link_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/click-details/{link_id}/members/{subscriber_hash}",
    "summary": "Get clicked link subscriber",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "link_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/domain-performance",
    "summary": "List domain performance stats",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/ecommerce-product-activity",
    "summary": "List campaign product activity",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "sort_field"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/eepurl",
    "summary": "List EepURL activity",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/email-activity",
    "summary": "List email activity",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "since"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/email-activity/{subscriber_hash}",
    "summary": "Get subscriber email activity",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "since"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/locations",
    "summary": "List top open activities",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/open-details",
    "summary": "List campaign open details",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "since",
      "sort_field",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/open-details/{subscriber_hash}",
    "summary": "Get opened campaign subscriber",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/sent-to",
    "summary": "List campaign recipients",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/sent-to/{subscriber_hash}",
    "summary": "Get campaign recipient info",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/sub-reports",
    "summary": "List child campaign reports",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/unsubscribed",
    "summary": "List unsubscribed members",
    "tag": "reports",
    "pathParams": [
      "campaign_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/reports/{campaign_id}/unsubscribed/{subscriber_hash}",
    "summary": "Get unsubscribed member",
    "tag": "reports",
    "pathParams": [
      "campaign_id",
      "subscriber_hash"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/",
    "summary": "List api root resources",
    "tag": "root",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/search-campaigns",
    "summary": "Search campaigns",
    "tag": "searchCampaigns",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "query"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/search-members",
    "summary": "Search members",
    "tag": "searchMembers",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "query",
      "list_id"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/surveys/{survey_id}/actions/create-email",
    "summary": "Create a Survey Campaign",
    "tag": "Surveys",
    "pathParams": [
      "list_id",
      "survey_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/surveys/{survey_id}/actions/publish",
    "summary": "Publish a Survey",
    "tag": "Surveys",
    "pathParams": [
      "list_id",
      "survey_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/lists/{list_id}/surveys/{survey_id}/actions/unpublish",
    "summary": "Unpublish a Survey",
    "tag": "Surveys",
    "pathParams": [
      "list_id",
      "survey_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/template-folders",
    "summary": "List template folders",
    "tag": "templateFolders",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/template-folders",
    "summary": "Add template folder",
    "tag": "templateFolders",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/template-folders/{folder_id}",
    "summary": "Delete template folder",
    "tag": "templateFolders",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/template-folders/{folder_id}",
    "summary": "Get template folder",
    "tag": "templateFolders",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/template-folders/{folder_id}",
    "summary": "Update template folder",
    "tag": "templateFolders",
    "pathParams": [
      "folder_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/templates",
    "summary": "List templates",
    "tag": "templates",
    "pathParams": [],
    "queryParams": [
      "fields",
      "exclude_fields",
      "count",
      "offset",
      "created_by",
      "since_date_created",
      "before_date_created",
      "type",
      "category",
      "folder_id",
      "sort_field",
      "content_type",
      "sort_dir"
    ],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/templates",
    "summary": "Add template",
    "tag": "templates",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/templates/{template_id}",
    "summary": "Delete template",
    "tag": "templates",
    "pathParams": [
      "template_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/templates/{template_id}",
    "summary": "Get template info",
    "tag": "templates",
    "pathParams": [
      "template_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "PATCH",
    "path": "/templates/{template_id}",
    "summary": "Update template",
    "tag": "templates",
    "pathParams": [
      "template_id"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/templates/{template_id}/default-content",
    "summary": "View default content",
    "tag": "templates",
    "pathParams": [
      "template_id"
    ],
    "queryParams": [
      "fields",
      "exclude_fields"
    ],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/verified-domains",
    "summary": "List sending domains",
    "tag": "verifiedDomains",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/verified-domains",
    "summary": "Add domain to account",
    "tag": "verifiedDomains",
    "pathParams": [],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "DELETE",
    "path": "/verified-domains/{domain_name}",
    "summary": "Delete domain",
    "tag": "verifiedDomains",
    "pathParams": [
      "domain_name"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "GET",
    "path": "/verified-domains/{domain_name}",
    "summary": "Get domain info",
    "tag": "verifiedDomains",
    "pathParams": [
      "domain_name"
    ],
    "queryParams": [],
    "hasBody": false
  },
  {
    "method": "POST",
    "path": "/verified-domains/{domain_name}/actions/verify",
    "summary": "Verify domain",
    "tag": "verifiedDomains",
    "pathParams": [
      "domain_name"
    ],
    "queryParams": [],
    "hasBody": false
  }
] as const;

export const ALL_TAGS: string[] = ["Surveys","accountExport","accountExports","activityFeed","audiences","authorizedApps","automations","batchWebhooks","batches","campaignFolders","campaigns","connectedSites","contacts","conversations","customerJourneys","ecommerce","facebookAds","fileManager","landingPages","lists","ping","reporting","reports","root","searchCampaigns","searchMembers","templateFolders","templates","verifiedDomains"];

export const TAG_DESCRIPTIONS: Record<string, string> = {
  "accountExport": "Export account data",
  "accountExports": "List account exports",
  "activityFeed": "Activity feed events",
  "authorizedApps": "OAuth authorized applications",
  "automations": "Marketing automation workflows and triggered emails",
  "batchWebhooks": "Batch webhook configurations",
  "batches": "Batch operations for bulk API calls",
  "campaignFolders": "Organize campaigns into folders",
  "campaigns": "Email campaigns — create, schedule, send, content, feedback",
  "connectedSites": "Connected e-commerce sites",
  "conversations": "Conversation tracking and messages",
  "customerJourneys": "Customer journey automations",
  "ecommerce": "E-commerce stores, products, orders, carts, customers",
  "facebookAds": "Facebook ad campaigns",
  "fileManager": "File and image uploads",
  "landingPages": "Landing page management",
  "lists": "Audiences — members, segments, merge fields, tags, webhooks, signups",
  "ping": "API health check",
  "reporting": "Advanced reporting and analytics",
  "reports": "Campaign performance reports — opens, clicks, bounces",
  "root": "API root and account info",
  "searchCampaigns": "Search campaigns by query",
  "searchMembers": "Search audience members by query",
  "surveyQuestions": "Survey question management",
  "surveyResponses": "Survey response data",
  "surveys": "Survey management",
  "templateFolders": "Organize templates into folders",
  "templates": "Email templates — create, update, manage",
  "verifiedDomains": "Domain verification for sending"
};
